language: cpp
sudo: required
distribution: trusty
os:
- linux
- osx
env:
- BADGE=linux
- BADGE=osx
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

compiler:
- gcc
- clang

before_install:
- sudo ./install.sh

script:
- sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-7 /usr/bin/g++
- sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
- cmake . 
- make clean
- make

after_install:
- sudo ./uninstall.sh

notifications:
  email: true
  # webhooks:
  #   urls:
  #   on_success: always
  #   on_failure: always
  #   on_start: always


